name: CI/CD Docker

on:
  push:
    branches: [ main, review-2 ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: Mestr3z
  IMAGE_PREFIX: ghcr.io/${{ env.OWNER }}/film

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Decide push flag
        id: push
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "push=true" >> $GITHUB_OUTPUT
          else
            echo "push=false" >> $GITHUB_OUTPUT
          fi

      - name: Build frontend-build
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: ${{ steps.push.outputs.push }}
          build-args: |
            VITE_API_URL=${{ vars.VITE_API_URL || 'http://localhost/api/afisha' }}
            VITE_CDN_URL=${{ vars.VITE_CDN_URL || 'http://localhost/content/afisha' }}
          tags: |
            ${{ env.IMAGE_PREFIX }}-frontend-build:latest
            ${{ env.IMAGE_PREFIX }}-frontend-build:${{ github.sha }}

      - name: Build backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64
          push: ${{ steps.push.outputs.push }}
          tags: |
            ${{ env.IMAGE_PREFIX }}-backend:latest
            ${{ env.IMAGE_PREFIX }}-backend:${{ github.sha }}

      - name: Build nginx
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          platforms: linux/amd64
          push: ${{ steps.push.outputs.push }}
          tags: |
            ${{ env.IMAGE_PREFIX }}-nginx:latest
            ${{ env.IMAGE_PREFIX }}-nginx:${{ github.sha }}
